### ISSUE TITLE
Auto trunc cutoff works really bad when high quality data

### ISSUE THREAD

**Issue by alneberg** [nf-core/ampliseq#135]
@FranBonath and I just finished running the nf-core/ampliseq pipeline. We ran into one issue where using the automatic choice of a cutoff did a very bad choice. In our case, using the default q-value of 25 gave us the cutoff 287, even though most reads were only 280 bp long. Re-reading the documentation, it becomes fairly obvious why this happened (q-value 25 too low for our data). In our case something like 99.9% of the reads were ignored. Choosing a manual cutoff at 275 bp solved our problem.

I'm not sure this really is a problem for the pipeline or just something the user should get used to. Maybe the script that picks the cutoff can make sure that there are more than just a few reads that make it to the cutoff. Otherwise, the docs can perhaps be updated to point out this issue even more clearly. What do you think? Feel free to close this issue if you feel it's up to the user to figure it out.

Cheers!

**Comment by d4straub** [comment]
Hi, thanks for the comment.

I usually set `--trunc_qmin 35` because this gives me with my high quality data good results. 25 (the default) was the recommendation in the QIIME2 forum, but this seems too low for all of my datasets. Choosing these values is somewhat arbitrary and it unfortunately always need to be checked after the run if the choice was good. But yes, it would be a great improvement if the script would check for read numbers as well and made sure that this is >90% or so.

**Comment by d4straub** [comment]
I agree it would be good to make sure the vast majority (e.g. 90%) of reads are longer than
the read length cutoff. A solution could be to either report an error if this isn't met or change cutoffs to a value that meets the majority of read lengths.

**Comment by d4straub** [comment]
This should be solved in the dev branch. By default, at least 75% of all reads are retained (`--trunc_rmin 0.75`), this will override `--trunc_qmin`. I did not use 90%, because I did have some datasets that had a relative variable read length (sequencing company did quality trimming already) and I do want that the required fraction of reads is only a safety net.
Thanks for your suggestion!
