### ISSUE TITLE
Add process that identifies sequences still containing primers

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#157]
In some cases, sequences contain duplicated primers. Only the first one will be removed by cutadapt and the processed sequence will hence contain a primer sequence. This is potentially an artifact from the PCR step.

Add a process that searches all ASV sequences for primers and output 1) a table (tsv file) that contains affected ASVs and 2) filtered tables containing information about all ASVs except those containing primers.

**Comment by erikrikarddaniel** [comment]
One possibility is to run cutadapt twice. The first time letting sequences through only if they contain the primers, the second time to *not* let sequences through if they still contain primers.

**Comment by erikrikarddaniel** [comment]
There's an `--discard-trimmed` option to `cutadapt` that can be used when cleaning up sequence pairs containing a second primer. @d4straub, this would be easy enough to implement but raises questions:

1. Do we want this step to be non-mandatory? If so, one needs to create another if block...
2. Does the `--retain_untrimmed` option to the workflow make sense?

I'd like to make the second cutadapt run mandatory and skip the `--retain_untrimmed`, to simplify the workflow.

**Comment by d4straub** [comment]
Ad 1: I am unsure how that second `cutadapt` run (`--discard-trimmed`) would effect results. Generally, I agree that reads should be after the first `cutadapt` run without any primer sequences (independent of using `--retain_untrimmed`), so the second `cutadapt` run discarding primer-containing reads should not break the analysis in any case. However, there might be unforseen complications and to keep the pipeline as broad as possible it might be good to make such a second run non-mandatory, but it seems ok to me to make it default.

Ad 2: Yes this option makes sense, because only primer trimmed reads might be available to the pipeline user. I'll like to have that in the pipeline, if at all possible.

**Comment by d4straub** [comment]
https://github.com/nf-core/test-datasets/pull/195 by @emnilsson prepared tests for this issue.

**Comment by d4straub** [comment]
This was addressed by the linked PR.
