### ISSUE TITLE
fastq filename convention and sample name parsing

### ISSUE THREAD

**Issue by janprovaz** [nf-core/ampliseq#182]
Hi Everyone! 

Sample name is parsed by splitting the filename on `_`.
This breaks when the sample names are different from `xxxx_L001_R{1,2}_001fastq.gz` or has an unexpected lack of `_`
In the [documentation](https://nf-co.re/ampliseq/1.1.3/parameters#input) it is not obvious, that one should have the `_L001_` in the filename.

I had samples named  `G0-3-2_R1_001.fastq.gz` with the `G0-3-2` being different sample names (only the numbers varied, single digits in all cases). 

Running with default parameters:
`./nextflow run nf-core/ampliseq -profile singularity --input reads --FW_primer GTGCCAGCMGCCGCGGTAA --RV_primer GGACTACHVGGGTWTCTAAT --metadata metadata.txt` 

Resulted in:
 ```
Error executing process > 'multiqc (1)'
Caused by:
  Process `multiqc` input file name collision -- There are multiple input files for each of the following file names: cutadapt/logs/cutadapt_log_.txt
```
notice the absence of the sample name in the file `cutadapt_log_.txt`

I renamed the input samples to:
`G032_L001_R1_001.fastq.gz` and it went through.
`G0-3-2_L001_R1_001.fastq.gz` also tested and also worked.

Proposed change:
Altering the documentation to reflect this, or changing the way the filenames are parsed in [main.nf](https://github.com/nf-core/ampliseq/blob/70b23f4710094df9299e5ab2d18a1d412bbd4d04/main.nf#L394)

Hope this helps 😄  
Thank you for your amazing work! 
All the best, 
Jan

**Comment by erikrikarddaniel** [comment]
This behaviour reflects how QIIME2 parses file names. For other file name patterns, you can use the `--manifest` option.

Documentation in `ampliseq` can probably be improved as you suggest.

**Comment by janprovaz** [comment]
Thank you, Daniel! Perfect :) 👍

**Comment by d4straub** [comment]
Actually, I think it should work with `--input`. The problem seems that the name (not read file, but the "pair_id" determined by e.g. [.fromFilePairs](https://github.com/nf-core/ampliseq/blob/dc4c62623a486314cd957af114db1b8e0c187480/main.nf#L417))  is splitted by `_` [here](https://github.com/nf-core/ampliseq/blob/dc4c62623a486314cd957af114db1b8e0c187480/main.nf#L419) but no `_` is found in the case you mention and therefore no name is given. I am not sure why I never came across that case!

**Comment by d4straub** [comment]
Fixed in dev.
