### ISSUE TITLE
"--double_primer" does not run cutadapt twice

### ISSUE THREAD

**Issue by emnilsson** [nf-core/ampliseq#197]
Found a bug in the code that's supposed to run cutadapt two times to remove double primers, even though the flag is set cutadapt is only run once.

**Comment by d4straub** [comment]
The two occurrences of `if [[ $params.double_primer == TRUE && $discard_untrimmed == "--discard-untrimmed" ]]; then` might need change in respect to:
- using curly brackets, such as `${params.double_primer}` instead of ` $params.double_primer`
- while `$discard_untrimmed == "--discard-untrimmed"` seems fine but `${params.retain_untrimmed} == true` is maybe more intuitive.
- the `== TRUE` part might be not necessary

**Comment by emnilsson** [comment]
I just changed `TRUE` to `true` and `$discard_untrimmed == --discard-untrimmed`, but I can try your suggested way instead. Maybe change the second one to `$params.retain_untrimmed == false` in any case (I assume it should be false, because if it is set double cutadapt should not be run, right?)?

**Comment by d4straub** [comment]
You are right, `$params.retain_untrimmed == false` instead of `true`, sure, sorry. But I do think `{}` should be used as above, therefore `${params.retain_untrimmed} == false`.

**Comment by emnilsson** [comment]
This should be fixed in the linked PR.
