### ISSUE TITLE
Error executing process > 'qiime_demux_visualize (demux)'

### ISSUE THREAD

**Issue by AaronHY** [nf-core/ampliseq#269]
I have met some problem to run my own data using ampliseq as below.  Could you please help with it? Thank you indeed.

nextflow run nf-core/ampliseq    -profile singularity     --input "test"     --FW_primer CCTACGGGRSGCAGCAG     --RV_primer GGACTACVVGGGTATCTAATC --max_cpus 10 --max_memory 65.GB

Error executing process > 'qiime_demux_visualize (demux)'

Caused by:
  Process `qiime_demux_visualize (demux)` terminated with an error exit status (1)

Command executed:

  export HOME="${PWD}/HOME"

  qiime demux summarize                 --i-data demux.qza              --o-visualization demux.qzv

  qiime tools export --input-path demux.qzv --output-path demux

Command exit status:
  1

Command output:
  (empty)

Command error:
  QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
  Plugin error from demux:

    Cannot describe a DataFrame without columns

  Debug info has been saved to /tmp/qiime2-q2cli-err-5stnmgqn.log

Work dir:
  /mnt/g/microtest2/work/0f/b5db21cd94522cbe3e941386105d2d

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by d4straub** [comment]
I think all your sequencing reads were lost in the first trimming step and therefore an empty data frame (without columns) arrived in the next step, where the error occurs. The trimming step is supposed to remove the primer sequence and if the primer sequence is not found, the read pair is discarded. You can check for trimming statistics for each sample in [results/trimmed/logs](https://nf-co.re/ampliseq/1.2.0/output#cutadapt).

I guess either your primer sequence is wrong or your data already had the primer sequence removed. So please make sure your primer sequence is correct. If indeed primer sequences were already removed beforehand, use the additional parameter[ `--retain_untrimmed`](https://nf-co.re/ampliseq/1.2.0/parameters#retain_untrimmed).

If your primers are correct, you have an apmlicon of around 465bp. If you have PE 250bp reads, this might be problematic with standard settings depending on your data quality. Read merging could be problematic. So please make sure to look at [results/abundance-table/unfiltered/dada_stats.tsv](https://nf-co.re/ampliseq/1.2.0/output#dada2) and make sure you retain >=50% of reads (except samples with really bad reads) and check the merging efficiency.

**Comment by d4straub** [comment]
In your above mentioned command 

> nextflow run nf-core/ampliseq -profile singularity --input "test" --FW_primer CCTACGGGRSGCAGCAG --RV_primer GGACTACVVGGGTATCTAATC --max_cpus 10 --max_memory 65.GB

the folder "test" is supposed to contain files with demultiplexed sequencing reads without Illumina adapters in compressed fastq format. Therefore, the pipeline does not require barcodes (those are only used for demultiplexing). `--FW_primer` and `--RV_primer` expect PCR primer strings. Those PCR primers are the sequences that match biological amplicons (i.e. not illumina adapters). Those primer sequences are used for two purposes: 
(1) primer removal from the sequencing reads it is important to remove all primer sequence added before ASV generation, otherwise it might not succeed or will be heavily biased
(2) trim the taxonomic database to the expected amplicon sequences, since this is improving performance of taxonomic classifications.

**Comment by d4straub** [comment]
Let me know in case you need further advice, I close it for now since there was no reply for 2 weeks.
