### ISSUE TITLE
Error executing process > 'alpha_diversity (evenness_vector)'

### ISSUE THREAD

**Issue by AaronHY** [nf-core/ampliseq#270]
Hi，after solving the problem with the data entry, I get stuck in the process of Alpha diversity as below. You assistance will be very much appreciated！

Error executing process > 'alpha_diversity (evenness_vector)'

Caused by:
  Process `alpha_diversity (evenness_vector)` terminated with an error exit status (1)

Command executed:

  export HOME="${PWD}/HOME"

  qiime diversity alpha-group-significance              --i-alpha-diversity evenness_vector.qza                 --m-metadata-file Metadata.tsv          --o-visualization evenness_vector-viv
  qiime tools export --input-path evenness_vector-vis.qzv               --output-path "alpha-diversity/evenness_vector"

Command exit status:
  1

Command output:
  (empty)

Command error:
  QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
  Plugin error from diversity:

    iteration over a 0-d array

  Debug info has been saved to /tmp/qiime2-q2cli-err-pg4uc217.log

Work dir:
  /mnt/g/microbiotest/work/74/022ce08f515694694b181c6afa02d0

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by d4straub** [comment]
> iteration over a 0-d array

seems again a problem with the data or metadata. A 0-dimensional array is missing data. Please check if (1) the ASV table is fine, (2) taxonomic classification seems alright, (3) rarefaction depth isnt too low, (4) metadata is fine.

Because we have discussed (1) in #269, I'd assume thats fine, (2) is usually ok, (3) & (4) might be rather the problem.
(3) if you have a very low count sample in your ASV table, but there should be a warning about it [here](https://github.com/nf-core/ampliseq/blob/1e76f1c0c6d270572573a6ad76aa40bfc185c3da/main.nf#L1752-L1755)
(4) the metadata could contain a faulty entry, hard to say.

**Comment by d4straub** [comment]
Let me know in case you need further advice, I close it for now since there was no reply for 2 weeks.
