### ISSUE TITLE
docker credentials needed

### ISSUE THREAD

**Issue by LeoWelter** [nf-core/ampliseq#346]
Docker needs credentials

# nf-core/ampliseq bug report
Command error:
  Unable to find image 'biocontainers/biocontainers:v1.2.0_cv1' locally
  docker: Error response from daemon: Head "https://registry-1.docker.io/v2/biocontainers/biocontainers/manifests/v1.2.0_cv1": unauthorized: incorrect username or password.
  See 'docker run --help'.

**Comment by d4straub** [comment]
When I run `nextflow run nf-core/ampliseq -r 1.2.0 -profile test,docker -resume` it does work without trouble. Also, that image `image 'biocontainers/biocontainers:v1.2.0_cv1'` should not be needed for ampliseq version 1.2.0 but from version 2.0.0 on. So that doesnt seem to me a bug in ampliseq but some sort of mixup an your side. If you give me more details (such as exact command you used, complete error message, .nextflow.log file for that run) than I might be able to be more specific.

**Comment by apeltzer** [comment]
Please logout from any logged in instances and try again:

`docker logout` should help in resolving this 👍🏻

**Comment by d4straub** [comment]
Hi there, due to lack of a response I close that issue. But please feel free to open another one in case you stumble upon other issues!

**Comment by LeoWelter** [comment]
Ok, sorry for not responding.
It was solved by login in through the docker desktop app


Op ma 15 nov. 2021 om 17:31 schreef Daniel Straub ***@***.***>
