### ISSUE TITLE
It seems like primer parameters are not used correctly in the dev version

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#367]
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/ampliseq pipeline documentation](https://nf-co.re/ampliseq/usage)

## Description of the bug

I just tried running the 2.2dev version for some old projects because I wanted to use the new SBDI-GTDB database, but the cutadapt process doesn't get the primer sequences. The `.command.sh` looks like this:

```#!/bin/bash -euo pipefail
cutadapt \
    --cores 6 \
    --minimum-length 1 -g null -G null --discard-untrimmed \
    -o P10813_1003.trimmed_1.trim.fastq.gz -p P10813_1003.trimmed_2.trim.fastq.gz \
    P10813_1003_1.fastq.gz P10813_1003_2.fastq.gz \
    > P10813_1003.trimmed.cutadapt.log
cat <<-END_VERSIONS > versions.yml
"NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT_BASIC":
    cutadapt: $(cutadapt --version)
END_VERSIONS
```

Both `-g` and `-G` gets `null`, and the run ends with the message: `cutadapt: error: Character 'L' in adapter sequence 'NTLL' is not a valid IUPAC code. Use only characters ABCDGHKMNRSTUVWXY.` (I suppose the "u" is translated to a "T" in "null"). My config file looks like this:

```
params {
  project       = "snic2021-22-263"
  input         = "samples.tsv"
  outdir        = "results"
  FW_primer     = "NNNNCCTACGGGNGGCWGCAG"
  RV_primer     = "GACTACHVGGGTATCTAATCC"
  trunclenf     = 259
  trunclenr     = 199
  double_primer = true
  skip_qiime    = true
  sample_inference  = "independent"
  dada_ref_taxonomy = "sbdi-gtdb"
  metadata      = 'lmo_16s_metadata.tsv'
  sbdiexport    = true
```

And the primers are correctly reported when the pipeline starts.

The stable version works fine. Nextflow updated today.

## Steps to reproduce

Steps to reproduce the behaviour:

`nextflow pull nf-core/ampliseq -r dev`
`nextflow run nf-core/ampliseq -r dev -profile NN` (I use the "uppmax" profile).

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: HPC
- Executor: slurm (uppmax profile)
- OS: 
- Version 

## Nextflow Installation

- Version: 21.10.6

## Container engine

- Engine: Singularity
- version:

**Comment by d4straub** [comment]
Hey,
that sounds bad! I have fiddled with the primer parameter (and some other) when updating the template to 2.2, see [here](https://github.com/nf-core/ampliseq/pull/362/files) in `nextflow.config`. Not sure where I went wrong, because I tested it. I will have a look tomorrow (today is a bank holiday).

**Comment by d4straub** [comment]
To conclude some discussion we had, also for later reference, `-c <file>.config` or a `nextflow.config` or such is not the correct way to set parameter (`params`) with nextflow. Instead, either the command line or `-params-file <file>.[yml,yaml,json]` are the correct way setting parameters.
Briefly, different config files seem to be sequentially read by nextflow and variables/conditions resolved, than the next config is read in. Because at the time of writing (version 2.1.1/2.2.0dev) several configs contain/reference parameter, e.g. `nextflow.config`, `conf/modules.config`, etc., and therefore can be differently resolved because params can have different values depending on in what sequence the config files are read. Essentially, using command line or `-params-file` takes priority over all other definitions and therefore make sure that all parameter are set identical at any point.
