### ISSUE TITLE
Using assignTaxonomy for PacBio CCS

### ISSUE THREAD

**Issue by proteinosome** [nf-core/ampliseq#387]
### Description of feature

Hi, thank you for developing this easy-to-use and comprehensive pipeline. I was testing out the pipeline for PacBio CCS data (ATCC-MSA1003 16S data available on PacBio's official website), and I found that a relatively low percentage of reads were assigned to species. I think this is because the pipeline uses "addSpecies" to handle species assignment which requires identical match. While this is important for short-reads, I believe it can be too harsh for long-reads. 

This is a Github issue where DADA2 dev Ben recommended using assignTaxonomy directly for long-reads (using the Silva tax file with the "wSpecies" suffix): https://github.com/benjjneb/dada2/issues/1122. May I know if there's a plan to implement this separately for PacBio CCS?

Thank you!

**Comment by d4straub** [comment]
Hi there, glad to hear the pipeline of use to you!
Thanks for bringing it up, that should definately go into the pipeline. I cannot really promise any timeline for the implementation though.

Essentially, the database [silva_nr99_v138.1_wSpecies_train_set.fa.gz](https://zenodo.org/record/4587955/files/silva_nr99_v138.1_wSpecies_train_set.fa.gz) should be made an option, probably even default with PacBio data. 

The workaround I was thinking of did _not_ work:
I attempted to use that database in the current version via `nextflow run nf-core/ampliseq -r 2.2.0 [...parameters...]  -c custom_ref_database.config --dada_ref_taxonomy "silva=138" -resume` where `custom_ref_database.config` contains:

```
params {
    dada_ref_databases {
        'silva=138' {
            title = "Silva 138.1 prokaryotic SSU with species"
            file = [ "https://zenodo.org/record/4587955/files/silva_nr99_v138.1_wSpecies_train_set.fa.gz", "https://zenodo.org/record/4587955/files/silva_species_assignment_v138.1.fa.gz" ]
            citation = "Quast C, Pruesse E, Yilmaz P, Gerken J, Schweer T, Yarza P, Peplies J, Glöckner FO. The SILVA ribosomal RNA gene database project: improved data processing and web-based tools. Nucleic Acids Res. 2013 Jan;41(Database issue):D590-6. doi: 10.1093/nar/gks1219. Epub 2012 Nov 28. PMID: 23193283; PMCID: PMC3531112."
            fmtscript = "taxref_reformat_standard.sh"
            dbversion = 'silva=138.1'
        }
    }
}
```
The problem seems the hard-coded taxonomic names and fields in [modules/local/dada2_taxonomy.nf](https://github.com/nf-core/ampliseq/blob/3beb2392044ad0575df76b54b0a5a26c6ce4b32a/modules/local/dada2_taxonomy.nf#L33-L56). Would it be possible to make that process more flexible with an optional `Species` column? Or probably even better: get that whole process more flexible and add that formatting into a separate process? Any idea @erikrikarddaniel ?

**Comment by erikrikarddaniel** [comment]
Yes, we should improve that. I had a quick talk with @jtangrot tody about this today as it's interesting for her long reads too. I have little time right now, I'm afraid.

**Comment by d4straub** [comment]
Hi @proteinosome , actually, QIIME2 is often rather a burden than a simplification in the framework of this pipeline. After I made QIIME2 (container) fit for nextflow, it appears that the latest 2 releases contain again changes that make it unusable. I will have to troubleshoot and possibly even again modify QIIME2 to make it work. It is a very large advantage to directly use DADA2 instead of using it gated behind QIIME2 (simplicity, flexibility, stability).

**Comment by d4straub** [comment]
Since #464 is merged, in the current dev branch (and will be in the next release) by default all databases that support Species annotation with assignTaxonomy (and that includes Silva 138) will do so and report the results (column "Species"). Additionally, by default, addSpecies is used for exact matches (column "Species_exact"). Thereby we provide choice to the user, but also put the responsibility to judge the relevance of the taxonomic classification to the user.

I'll close that now.
