### ISSUE TITLE
DADA2 quality step error: The filter removed all reads

### ISSUE THREAD

**Issue by Namelya23** [nf-core/ampliseq#419]
### Description of the bug

I have16S rRNA seq with paired-end data (iseq 100, illumina)  from fecal samples and we want to run ampliseq for detecting population of bacteria. I've read similar posts, most of which suggested to adjust --trunc_qmin, --trunclenr and --trunclenf. However, I tried to use these parameters, it seemed not to work for me. I do not understand how can I use these parameters? So I upload my error and results here and ask for help. Can you give me some suggestions? Thank you very much.

When I run the script below, I got this error. 
![image](https://user-images.githubusercontent.com/97851787/162229047-235a2cb6-643a-43ac-a691-a9edd2148043.png)
 

### Command used and terminal output

```console
nextflow run nf-core/ampliseq \
    -profile docker \
    -c ibg.config \
    --input "/home/binokayl/Solaris/fekal_ampliseq_analiz/scripts/samplesheet.tsv" \
    --metadata "/home/binokayl/Solaris/fekal_ampliseq_analiz/scripts/metadata.tsv" \
    --FW_primer TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG \
    --RV_primer GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC \
    --multiple_sequencing_runs \
    --picrust \
    --dada_ref_taxonomy "silva=138"  \
    --outdir "/home/binokayl/Solaris/fekal_ampliseq_analiz/results/"

config dosyası ibg2.config:
process {
      withName:QIIME2_ALPHARAREFACTION {
          cpus = 24
          memory = 100.GB
          time = 240.h
    }
}


    Execution cancelled -- Finishing pending tasks before exit
    -[nf-core/ampliseq] Pipeline completed with errors-
    WARN: Probably everything is fine, but this is a reminder that `--trunclenf` was set automatically to 57 and `--trunclenr` to 134. If this doesnt seem reasonable, then please change `--trunc_qmin` (and `--trunc_rmin`), or set `--trunclenf` and `--trunclenr` directly.
    Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:DADA2_FILTNTRIM (S15)'

    Caused by:
      Missing output file(s) `*.filt.fastq.gz` expected by process `NFCORE_AMPLISEQ:AMPLISEQ:DADA2_FILTNTRIM (S15)`

    Command executed:

      #!/usr/bin/env Rscript
      suppressPackageStartupMessages(library(dada2))

      out <- filterAndTrim("S15.trimmed_1.trim.fastq.gz", "S15_1.filt.fastq.gz", "S15.trimmed_2.trim.fastq.gz", "S15_2.filt.fastq.gz",
          truncLen = c(57, 134),
          maxN = 0, truncQ = 2, trimRight = 0, minQ = 0, rm.lowcomplex = 0, orient.fwd = NULL, matchIDs = FALSE, id.sep = "\\s", id.field = NULL, n = 1e+05, OMP = TRUE, qualityType = "Auto",maxEE = c(2, 2),trimLeft = 0, minLen = 50, maxLen = Inf, rm.phix = TRUE,
          compress = TRUE,
          multithread = 6,
          verbose = TRUE)
      out <- cbind(out, ID = row.names(out))

      write.table( out, file = "S15.filter_stats.tsv", sep = "\t", row.names = FALSE, quote = FALSE, na = '')
      write.table(paste('filterAndTrim      truncLen = c(57, 134)','maxN = 0, truncQ = 2, trimRight = 0, minQ = 0, rm.lowcomplex = 0, orient.fwd = NULL, matchIDs = FALSE, id.sep = "\\s", id.field = NULL, n = 1e+05, OMP = TRUE, qualityType = "Auto",maxEE = c(2, 2),trimLeft = 0, minLen = 50, maxLen = Inf, rm.phix = TRUE',sep=","), file = "filterAndTrim.args.txt", row.names = FALSE, col.names = FALSE, quote = FALSE, na = '')
      writeLines(c("\"NFCORE_AMPLISEQ:AMPLISEQ:DADA2_FILTNTRIM\":", paste0("    R: ", paste0(R.Version()[c("major","minor")], collapse = ".")),paste0("    dada2: ", packageVersion("dada2")) ), "versions.yml")

    Command exit status:
      0

    Command output:
      (empty)

    Command error:
      The filter removed all reads: S15_1.filt.fastq.gz and S15_2.filt.fastq.gz not written.
      Warning message:
      In filterAndTrim("S15.trimmed_1.trim.fastq.gz", "S15_1.filt.fastq.gz",  :
        No reads passed the filter. Please revisit your filtering parameters.

    Work dir:
      /home/binokayl/Solaris/fekal_ampliseq_analiz/work/e4/93dd78024abbcaa4b056018634440d

    Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### Relevant files

[nextflow.log](https://github.com/nf-core/ampliseq/files/8444048/nextflow.log)

### System information

Nextflow 21.10.6
nf-core/ampliseq 2.3.1
Centos 7.5
Ram 384GB
CPU Intel XEONGold 40Core
Docker 20.10.5

**Comment by d4straub** [comment]
Hi there!

I'll try to help:
- the primer sequences seem wrong, please see [--FW_primer](https://nf-co.re/ampliseq/2.3.1/parameters#fw_primer):

> Do not use here any technical sequence such as adapter sequences but only the primer sequence that matches the biological amplicon.

However, you supply primer sequences that are very long and certainly include Illumina adapter/etc. sequences. I assume your real primers are `CCTACGGGNGGCWGCAG` (341F) and `GACTACHVGGGTATCTAATCC` (805R), if that is true, please use 
`--FW_primer CCTACGGGNGGCWGCAG --FW_primer GACTACHVGGGTATCTAATCC`

- The warning message also seems to indicate that something is wrong:

> WARN: Probably everything is fine, but this is a reminder that `--trunclenf` was set automatically to 57 and `--trunclenr` to 134. If this doesnt seem reasonable, then please change `--trunc_qmin` (and `--trunc_rmin`), or set `--trunclenf` and `--trunclenr` directly.

I usually expect the reverse trimming `--trunclenr` to be smaller than the forward trimming `--trunclenf`, because the forward reads have typically better quality with Illumina. But your `--trunclenr` is automatically set to 134 while `--trunclenf` is at 57.

After you have tested with correct primer sequences, you will encounter that the length thresholds will be chosen differently. For the primers above, the amplicon length is expected to be ~464bp, additional 20bp for read merging is required, therefore `--trunclenf` and `--trunclenr` should sum to about 480, ideally a little more.

Let me know how it goes, best of luck!

**Comment by lemanbinokay23** [comment]
Hi again,
Thank you for your help, we realized that the problem was caused by sequencing step. I want to ask one last question. Is Nf-core/ampliseq pipeline suitable for nanopore sequencing data? Thank you very much.

**Comment by d4straub** [comment]
Hi,
glad you found the source of the problem!
nf-core/ampliseq is currently not able to use nanopore data. Nanopore data is to my knowledge not very well suited (yet) for amplicon analysis due to its relatively high error rate. I think there are ways to handle such data, i.e. using vsearch and cluster & quantify data. But this isnt supported in nf-core/ampliseq.

If you have another problem/question, feel free to open a new issue.
Best of luck!
