### ISSUE TITLE
Add VSEARCH/SINTAX taxonomy annotation

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#471]
### Description of feature

The SINTAX algorithm by Robert Edgar is apparently better for certain taxa/databases, primarily by being more strict and not providing so many false positives. Add as alternative to `assignTaxonomy`.

**Comment by jtangrot** [comment]
I started working on this and need some advice how to integrate it into the workflow. 
* I'm considering two options to make it run sintax; either to add an option --sintax to tell it to use that, and have a default taxonomy database if none is given with a second option --sintax_ref_taxonomy, or to just use --sintax_ref_taxonomy and run sintax if that is given (i.e. no --sintax option and no default sintax database). Any thoughts?
* Should sintax be used as a replacement for assignTaxonomy, i.e. should the results be sent into qiime for downstream analyses? Or is it better to have it as an extra option that is possible to run in addition to assignTaxonomy?

**Comment by d4straub** [comment]
> I'm considering two options to make it run sintax; either to add an option --sintax to tell it to use that, and have a default taxonomy database if none is given with a second option --sintax_ref_taxonomy, or to just use --sintax_ref_taxonomy and run sintax if that is given (i.e. no --sintax option and no default sintax database). Any thoughts?

`--sintax_ref_taxonomy` is sufficient, I think. Only if sintax runs by default, a `--skip_sintax` would be needed, imho.

> Should sintax be used as a replacement for assignTaxonomy, i.e. should the results be sent into qiime for downstream analyses?

Yes, I think the results should be send into QIMME2, if possible. But I would only forward one taxonomy per run. At the moment when DADA2 _and_ QIIME2 are used for taxonomic assignment, DADA2 results are preferred. See help of [--qiime_ref_taxonomy](https://nf-co.re/ampliseq/2.5.0/parameters#qiime_ref_taxonomy) -> `If both, --dada_ref_taxonomy and --qiime_ref_taxonomy are used, DADA2 classification will be used for downstream analysis.`. Maybe sintax can be put into that priority list? This is encoded [here](https://github.com/nf-core/ampliseq/blob/78b7514ceeba80efb66b0e973e5321878cb9b0ba/workflows/ampliseq.nf#L498-L519).

> Or is it better to have it as an extra option that is possible to run in addition to assignTaxonomy?

I imagine one could run all 3 taxonomic assignment methods in future simultaneously to compare, i.e. run sintax in addition to assignTaxonomy. But as above, only one forwarded to downstream analysis (otherwise there is a huge runtime overhead).

**Comment by d4straub** [comment]
Is that solved?

**Comment by jtangrot** [comment]
Solved in #577
