### ISSUE TITLE
nf-tower: when choosing the test profile, setting a pre-trained classifer for QIIME2 leads to "Incompatible parameters: `--qiime_ref_taxonomy` & `--classifier`"

### ISSUE THREAD

**Issue by mdyoungblut** [nf-core/ampliseq#485]
### Description of the bug

I'm trying to use `qiime_ref_taxonomy: null` and set a particular classifier via `classifier: ` (via an nf-tower config yaml file). nf-tower doesn't seem to allow for `qiime_ref_taxonomy: null` and instead sets `qiime_ref_taxonomy` to greengenes85. In the run error logs that lists all parameters set for the pipelines:

```
[0;34mqiime_ref_taxonomy        : [0;32mgreengenes85[0m
```

This auto-setting of `qiime_ref_taxonomy: greengenes85` results in the error:

```
Incompatible parameters: `--qiime_ref_taxonomy` will produce a classifier but `--skip_classifier` points to a precomputed classifier, therefore, only use one of those.
```

due to:

```
        if (params.qiime_ref_taxonomy && params.classifier) {
            log.error "Incompatible parameters: `--qiime_ref_taxonomy` will produce a classifier but `--skip_classifier` points to a precomputed classifier, therefore, only use one of those."
            System.exit(1)
        }
```

It appears that there's something funky going on with https://github.com/nf-core/ampliseq/blob/master/nextflow_schema.json in regards to what is allowed (e.g., allowing `null` in nf-tower). 

This issue should be easy to reproduce.

### System information

nf-tower

**Comment by mdyoungblut** [comment]
Even when I select "None" for qiime_ref_taxonomy in the parameters settings for the nextflow run, I get `[0;34mqiime_ref_taxonomy        : �[0;32mgreengenes85�[0m` in the execution log. It appears that `None` is ignored in nf-tower and `greengenes85` is always used

**Comment by d4straub** [comment]
Hi there,
that seems indeed unfortunate. I am not using nf-tower and therefore not sure how that works with the yaml (and cannot test it quickly).
Could you test `false` instead of `null`?
It might be also helpful to have the complete yaml file copy-pasted here, and additionally to have the run error logs with parameters listed to see whether/what params are correctly set and which not.

Also, in that error message, `--skip_classifier` is a typo and should be obviously `--classifier`, will note that down.

**Comment by d4straub** [comment]
`qiime_ref_taxonomy` is by default set to `null`, see https://github.com/nf-core/ampliseq/blob/708b8398d007d9a8c907ce6da478717e1ab5f5bc/nextflow.config#L83
Something else seems to have set it to greengenes85. This raises again the importance of more information.

**Comment by mdyoungblut** [comment]
>I am not using nf-tower and therefore not sure how that works with the yaml (and cannot test it quickly).

Personal nf-tower accounts are free, so it should be easy to test.

>Could you test false instead of null?

The nf-tower parameter web page shows a list of all possible options (e.g., `greengenes85`) and just one extra option: `None`. So, I cannot select `false` from the list. If I try to use `qiime_ref_taxonomy    = null` (the default), then the nf-tower parameter page shows `None` for the option selected

>Something else seems to have set it to greengenes85. This raises again the importance of more information.

There's really nothing else special about my parameter settings besides using `qiime_ref_taxonomy  = null`

**Comment by mdyoungblut** [comment]
I think that I know why `greengenes85` is selected. I'm using the `docker` and `test` profiles for the nextflow runs, since nf-tower requires a "job launcher" with pre-set profiles. So, including the `test` profile means that the nf-tower job will run with default (test) settings, without having to provide any other settings (useful for quick testing of the pipeline on AWS). 

However, it appears that I cannot then override `qiime_ref_taxonomy: greengenes85` by uploading a parameters yaml file that includes `qiime_ref_taxonomy: null`

**Comment by d4straub** [comment]
Alright, we are coming closer to identifying the problem.

> I think that I know why greengenes85 is selected. I'm using the docker and test profiles for the nextflow runs, since nf-tower requires a "job launcher" with pre-set profiles. 

Yes, thats it.

> However, it appears that I cannot then override qiime_ref_taxonomy: greengenes85 by uploading a parameters yaml file that includes qiime_ref_taxonomy: null

This is curious and I also would expect that there is a way to override test settings.

As I am not familiar with nf-tower, I would like to forward you either to [nf-core](https://nf-co.re/join) [slack](https://nf-co.re/join/slack) channel help (because I do not know a more appropriate channel for that problem) of nf-tower support.

**Comment by d4straub** [comment]
I did ask myself in the nextflow slack channel tower-help, to no avail though. So I cannot provide a solution here.
I do hope that this was some sort of problem because of using the test profile and that this isnt needed usually.
Anyway, if anyone has persistent problems with this pipeline in combination with nf-tower, please raise your voice (or better: write an issue!).
