### ISSUE TITLE
Please upload the environment.yml file

### ISSUE THREAD

**Issue by karnival21** [nf-core/ampliseq#499]
### Description of feature

I am trying to use the environment.yml file to create a new conda environment, but I can't find it. Can you upload the environment.yml file, please?

**Comment by d4straub** [comment]
There is no `environment.yml` any more. The `environment.yml` was last used in version 1.2.0, and I cannot recommend using that version. Since version 2.0.0 the pipeline is written in nextflow DSL2 syntax (instead of DSL2, which used the `environment.yml`). Now the pipeline uses its own container/conda environment for each process.
You can run the current pipeline version pipeline with `nextflow run nf-core/ampliseq -r 2.4.0 -profile test,conda --outdir results_test --skip_qiime`, the last parameter will omit any downstream analysis with qiime2 because that doesnt support a straight forward conda environment. I'd recommend using one of the container programs like docker or singularity though.

**Comment by d4straub** [comment]
I am closing this but please feel free to open another issue when coming across a problem.
