### ISSUE TITLE
Parallelization processes in DADA2_DENOISE and RM_CHIMERAS

### ISSUE THREAD

**Issue by sgaleraalq** [nf-core/ampliseq#523]
### Description of feature

Hi guys!

I was wondering if there is any command or options that you can add in the .config file to add parallelization in the DADA2_DENOISE and RM_CHIMERAS step, i.e. send every sample to a different node and merge all of them after they have finished with the processes. I have seen that some processes, like FILTNTRIM does that in a cluster and if it could be possible to implement it in those pipeline steps it will speed up the running time of the workflow significantly.

Thank you very much!

**Comment by d4straub** [comment]
Hi there, thanks for the suggestion.

I do not think it is possible to use the config to parallelize those steps currently. You can however use the column "run" in the samplesheet to split samples into batches and process in parallel (see https://nf-co.re/ampliseq/2.4.1/usage#samplesheet-input). But that will also split those earlier for calculating the error model, and that is not recommended if the samples are from the same sequencing run, see [here](https://nf-co.re/ampliseq/2.4.1/usage#quick-start) (scroll down to figure) how that works. On the other hand, if you do not split into too small batches, the results should be almost or truly identical. If you use non-default settings for [`--sample_inference`](https://nf-co.re/ampliseq/2.4.1/parameters#sample_inference), do not split artificially, because there I would expect trouble (those other settings require information of all samples).
You can, though, allocate more CPUs to processes with configs, resource adjustments are described [here](https://nf-co.re/ampliseq/2.4.1/usage#resource-requests). That should also help considerably.

About adding such a possibility: That should work depending on denoising settings. The default setting, [`--sample_inference "independent"`](https://nf-co.re/ampliseq/2.4.1/parameters#sample_inference) handles samples independent (at least the description says so) and process in parallel should work. But other settings (pseudo/pooled), which I highly recommend, wont work when splitting as far as I know.

If you have any idea or information how that might work, let me know, I am happy to learn!

**Comment by sgaleraalq** [comment]
Thank you very much for your fast answer! I believe that --sample_inference "independent"will make the fastest processes of them all but it still takes some time to run. I have tried with the maximum number of CPUs available but since my dataset is quite huge (~300 samples) it takes a lot of time.

Another thing that would be useful could be to add a --skip for dada2 pipelines so that if parallelization is not available, one can make the denoise on a separate workflow and then add it to nf-core pipeline. But that is just a suggestion :)

**Comment by d4straub** [comment]
> --sample_inference "independent"will make the fastest processes

That is correct, other methods will increase runtime by a lot.

> my dataset is quite huge (~300 samples) it takes a lot of time

Depending on your data and cpu resources, it might take a night/day or so, but should be manageable.
Taxonomic classification might be also time consuming, depending on the number of ASVs. But those can be filtered by length, prevalence or abundance if needed.

> Another thing that would be useful could be to add a --skip for dada2 pipelines so that if parallelization is not available, one can make the denoise on a separate workflow and then add it to nf-core pipeline. 

I am not very convinced, because the DADA2 part is sort of important in the pipeline I think.

**Comment by sgaleraalq** [comment]
Then I must be doing something incorrect because takes at least 3 days for me to finish with the DENOISING step. 

> I am not very convinced, because the DADA2 part is sort of important in the pipeline I think.

I was just saying to be an optional parameter, just in case you dont want to use it! But I see your point that is pretty important.

**Comment by d4straub** [comment]
3 days is indeed a little much, but if you have an unusual high sequencing depth and very divers samples (many different taxa per sample but also between samples) it might take long. Let me know whether you give it time and whether the process progresses. You also might investigate from time to time whether the job indeed is running and not stalling because of some sort of error.

**Comment by d4straub** [comment]
@sgaleraalq any news?

**Comment by sgaleraalq** [comment]
It is still taking so long for my samples. I use these parameters which I think they should be enough for 300 samples, what do you think about it? Maybe I'm using not so many RAM?

```
withName:DADA2_ERR {
    memory = 115.GB
    cpus = 20
    time = 167.h
  }
  withName:DADA2_RMCHIMERA {
    memory = 115.GB
    cpus = 20
    time = 167.h
  }
    withName:DADA2_DENOISING {
    memory = 115.GB
    cpus = 20
    time = 167.h
  }
```

My cluster always kills the process because it exceeds the maximum time permited. I really do not know what to do to make it faster.

**Comment by d4straub** [comment]
Maybe it would be possible to do more aggressive quality filtering to reduce the number of bases that come into the three processes that you list here.

Some possibilities (not exhaustive): 
- be more strict with primer matches: [--cutadapt_min_overlap 10](https://nf-co.re/ampliseq/2.4.1/parameters#cutadapt_min_overlap ) [--cutadapt_max_error_rate 0](https://nf-co.re/ampliseq/2.4.1/parameters#cutadapt_max_error_rate)
- cut reads shorter for less errors and bases to use: [--trunc_qmin 35](https://nf-co.re/ampliseq/2.4.1/parameters#trunc_qmin), or use manually https://nf-co.re/ampliseq/2.4.1/parameters#trunclenf & https://nf-co.re/ampliseq/2.4.1/parameters#trunclenr
- only use reads of lower expected errors: [--max_ee 0](https://nf-co.re/ampliseq/2.4.1/parameters#max_ee)

You can check the [read count report](https://nf-co.re/ampliseq/2.4.1/output#read-count-report) to see where many reads are lost and if thats fine to you. If that isnt available check `results/cutadapt/cutadapt_summary.tsv` and `results/dada2/QC/*qual_stats.pdf`

**Comment by d4straub** [comment]
I have one more idea: split into different runs, i.e. fill out different run ids (3-10) in column "run" of the sample sheet. See end of section https://nf-co.re/ampliseq/2.14.0/docs/usage/#quick-start and  https://nf-co.re/ampliseq/2.14.0/docs/usage/#samplesheet-input. Samples for each unique run id will create a batch that is individually denoised and chimera removed. That should speed up the process considerably.

**Comment by HannahBenisty** [comment]
Thanks!
I’m currently running with pseudo, but given the large number of samples, I’m wondering if it would be better to use independent instead to keep things more stable. Even if that means losing some low-abundance ASVs.
