### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by a4000** [nf-core/ampliseq#635]
### Description of the bug

In the usage section of README.md, there's a link to the parameter documentation (https://nf-co.re/ampliseq/parameters). When I follow this link, I get a 404 error. I found the correct parameter documentation when I include the version number in the link (https://nf-co.re/ampliseq/2.6.1/parameters/). I think the easiest fix to this issue is to update the link in README.md to have the version number, but that means someone will need to remember to update the link for every new version.

**Comment by d4straub** [comment]
Thanks for the report!
Not sure this is an ampliseq problem, because those links work as expected (all linking to the most recent release):
https://nf-co.re/ampliseq/usage
https://nf-co.re/ampliseq/usage#metadata
https://nf-co.re/ampliseq/output
https://nf-co.re/ampliseq/results
the only one that fails is:
https://nf-co.re/ampliseq/parameters
Will investigate, thanks again!

**Comment by d4straub** [comment]
Update: that seems a website bug, I think links should re-direct. I opened the above linked issue at the nf-core website. Therefore, in the nf-core/ampliseq specific context, this is clarified. I hope it will be fixed soon ;)
