### ISSUE TITLE
Requirement Exceeds Available Memory for CUTADAPT

### ISSUE THREAD

**Issue by aqsakhalid03** [nf-core/ampliseq#650]
### Description of the bug

I am getting memory requirement error, however, i have provided the custom.config file to resolve this but i am getting the same issue. 

### Command used and terminal output

```console
Command: nextflow run nf-core/ampliseq     -r 2.3.2     -profile docker    --input input/Samplesheet.tsv   --FW_primer GTGYCAGCMGCCGCGGTAA     --RV_primer GGACTACNVGGGTWTCTAAT     --metadata "input/Metadata.tsv" -c custom_ampliseq.config  --skip_diversity_indices --outdir test_FF_data 

The custom_ampliseq.config file i have used is below: 
process {
    cpus = 36
    memory = 42.GB
}

ERROR
-[nf-core/ampliseq] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT_BASIC (CA-S10009-T2-LAB)'

Caused by:
  Process requirement exceeds available memory -- req: 42 GB; avail: 31 GB

Command executed:

  cutadapt \
      --cores 6 \
      --minimum-length 1 -O 3 -e 0.1 -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT --discard-untrimmed \
      -o CA-S10009-T2-LAB.trimmed_1.trim.fastq.gz -p CA-S10009-T2-LAB.trimmed_2.trim.fastq.gz \
      CA-S10009-T2-LAB_1.fastq.gz CA-S10009-T2-LAB_2.fastq.gz \
      > CA-S10009-T2-LAB.trimmed.cutadapt.log
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT_BASIC":
      cutadapt: $(cutadapt --version)
  END_VERSIONS

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /home/aqsakhalid/work/2f/5bf38b019a68db746486da602383bc

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Comment by d4straub** [comment]
Hi there,

it says `Process requirement exceeds available memory -- req: 42 GB; avail: 31 GB`, meaning your config indeed seems to work , it request 42 GB (req: 42 GB) but it fails because only 31 GB are available (avail: 31 GB). Therefore it seem to me that only 31GB were available at the time of execution. As far as I see you do not use a scheduler, such as slurm or such? If you are on a hpc better ask your sys admin what sheduler and node setup your hpc has to use it properly.
Apart from this, cutadapt usually doesnt need so much memory, do you have unusally large files (lets say, >1GB)?

Also, if you have the choice, could you use the most recent release (2.6.1) instead of an old release (you seem to use 2.3.2)?

**Comment by aqsakhalid03** [comment]
Yeah i have only 31 GB available memory on my system but i try to run it using external hard drive of 3TB memory but i am still facing the same issue. I don't have hpc. Is it possible to run it using external drive ? or any other way to resolve memory issue? I can try the recent release as well.

**Comment by d4straub** [comment]
Unfortunately "memory" means here RAM, not disk space. So no, it wont work with an external hard drive.
You can try to use instead of your config rather [--max_memory](https://nf-co.re/ampliseq/2.6.1/parameters#max_memory), set it to the maximum amount of RAM you have, e.g. `--max_memory '31.GB'`. If you have a small dataset that might be sufficient. Problematic might be taxonomic classification, but that might be possible to solve once you encounter the problem.

**Comment by aqsakhalid03** [comment]
When i try to use the ` --max_memory '31.GB'`  flag. I am not able to add the species in the taxonomy classification for DADA2. and i encounter with below error. 
`nextflow run nf-core/ampliseq     -r 2.3.2     -profile docker    --input input/Samplesheet.tsv   --FW_primer GTGYCAGCMGCCGCGGTAA     --RV_primer GGACTACNVGGGTWTCTAAT     --metadata "input/Metadata.tsv"  --skip_diversity_indices --skip_qiime2  --max_memory '31.GB' --outdir test_FF_data 
`
ERROR: 
-[nf-core/ampliseq] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_ANCOM:QIIME2_ANCOM_TAX (treatment1 - taxonomic level: 2)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_ANCOM:QIIME2_ANCOM_TAX (treatment1 - taxonomic level: 2)` terminated with an error exit status (1)

Command executed:

  export XDG_CONFIG_HOME="${PWD}/HOME"
  mkdir ancom
  
  # Sum data at the specified level
  qiime taxa collapse             --i-table treatment1.qza             --i-taxonomy taxonomy.qza             --p-level 2             --o-collapsed-table lvl2-treatment1.qza
  
  # Extract summarised table and output a file with the number of taxa
  qiime tools export --input-path lvl2-treatment1.qza --output-path exported/
  biom convert -i exported/feature-table.biom -o treatment1-level-2.feature-table.tsv --to-tsv
  
  if [ $(grep -v '^#' -c treatment1-level-2.feature-table.tsv) -lt 2 ]; then
      echo 2 > ancom/"WARNING Summing your data at taxonomic level 2 produced less than two rows (taxa), ANCOM can't proceed -- did you specify a bad reference taxonomy?".txt
  else
      qiime composition add-pseudocount                 --i-table lvl2-treatment1.qza                 --o-composition-table comp-lvl2-treatment1.qza
      qiime composition ancom                 --i-table comp-lvl2-treatment1.qza                 --m-metadata-file Metadata.tsv                 --m-metadata-column treatment1                 --o-visualization comp-lvl2-treatment1.qzv
      qiime tools export --input-path comp-lvl2-treatment1.qzv                 --output-path ancom/Category-treatment1-level-2
  fi
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_ANCOM:QIIME2_ANCOM_TAX":
      qiime2: $( qiime --version | sed -e "s/q2cli version //g" | tr -d '`' | sed -e "s/Run qiime info for more version details.//g" )
  END_VERSIONS

Command exit status:
  1

Command output:
  Saved FeatureTable[Frequency] to: lvl2-treatment1.qza
  Exported lvl2-treatment1.qza as BIOMV210DirFmt to directory exported/

Command error:
  QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-rzakp3tr because the default path (/home/qiime2/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  Saved FeatureTable[Frequency] to: lvl2-treatment1.qza
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-j89uxeno because the default path (/home/qiime2/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  Exported lvl2-treatment1.qza as BIOMV210DirFmt to directory exported/
  .command.sh: line 13: ancom/WARNING Summing your data at taxonomic level 2 produced less than two rows (taxa), ANCOM can't proceed -- did you specify a bad reference taxonomy?.txt: Invalid argument

**Comment by d4straub** [comment]
Can you please use `-r 2.7.0` ? That would be the latest version. the command doesnt change otherwise. Do as follows:
```
nextflow pull nf-core/ampliseq
nextflow pull nf-core/ampliseq -r 2.7.0
nextflow run nf-core/ampliseq -r 2.7.0 [... your parameter ...]
```

> I am not able to add the species in the taxonomy classification for DADA2. 

Yes, the default SILVA v138 database with DADA2 requires more memory because its huge. You can use a smaller database that will require less memory. For example, add to your command `--dada_ref_taxonomy "gtdb=R08-RS214"` that will use the latest GTDB database which is smaller (less sequences -> less RAM required) but of great quality.

**Comment by d4straub** [comment]
Any news here? If your problem is resolved please close the issue.

**Comment by d4straub** [comment]
I close the issue for now, please open another one when encountering any problem!
