### ISSUE TITLE
Abundance plots for qiime2 results without metadata provided

### ISSUE THREAD

**Issue by SergeWielhouwer** [nf-core/ampliseq#738]
### Description of feature

Hi,

Thanks for developing Ampliseq!

I was wondering whether a metadata file is really necessary for the visualisation of the relative microbial abundance per sample. Currently, QIIME2 barplots (HTML) are available in addition to the different level tsv tables when providing such files, but when running without this file no visualisations are available for the taxonomic classification part. These plots really help to get a quick overview of the different compositions of all samples without any data wrangling. Are there any plans to add such visualisations (Krona, QIIME2) to the output when no differential abundance analysis (i.e. no metadata file given) is performed?

I am currently using matplotlib on the relative qiime2 tables as an alternative, but would love to see some (interactive) plots readily available from the pipeline output :). I am currently on version v2.9.0. 

`/mnt/shared/tools/nextflow-23.10.1/nextflow run /mnt/shared/development/16Smicrobiome/ampliseq-2.9.0/main.nf -profile singularity --input samplesheet.tsv --FW_primer "TATGGTAATTGTGTGCCAGCMGCCGCGGTA" --RV_primer "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATC" --retain_untrimmed --outdir output -resume`

Best regards,

Serge

**Comment by d4straub** [comment]
I think metdata is not required by the function the produces barplots. However, the pipeline requires it, thats a relict of the past when metadata was indeed necessary for producing barplots. Thats a good point and should be fixed for the next release.

For now, you could give it a metadata file with one "fake" category so that the barplot is produced (and skip whatever you do not like via parameters).

**Comment by SergeWielhouwer** [comment]
That would be great, Thanks!
