### ISSUE TITLE
Latest release seems to have done anyway with the ability to specify `--max_memory` - can this be restored?

### ISSUE THREAD

**Issue by agrier-wcm** [nf-core/ampliseq#814]
### Description of the bug

Hello,

Not sure if this is a bug or a design decision, but release 2.12.0 seems to have done away with the ability to specify `--max_memory` (and time and cpus).  Is this intentional and if so what is the rationale?

### Command used and terminal output

```console

```

**Comment by d4straub** [comment]
Hi there,

I apologize I forgot to add that info actually to the CHANGELOG, and that would have been important, I agree. The removal of `--max_memory`, `--max_cpus`, and `--max_time` was by design.

It was a change by the nf-core pipeline template, see [this blog post](https://nf-co.re/blog/2024/tools-3_0_0#the-check_max-function-has-been-removed). Essentially, the nf-core way of dealing with upper limits for memory, cpus, and time was replaced by the nextflow functionality called [resourceLimits](https://www.nextflow.io/docs/latest/reference/process.html#resourcelimits).

Essentially, now the resource limits are not set via the command line any more but via a config file using `-c`. See for example [this file](https://github.com/nf-core/configs/blob/1f1658b93045df7cd7d68301f1fc08483c411f78/conf/cfc.config#L13-L18).

Does that answer your question sufficiently?

**Comment by d4straub** [comment]
Yes, the code above for version 2.12.0 is equal to `--max_cpus 16 --max_memory 32.GB --max_time 72.h` for version 2.11.0.
