### ISSUE TITLE
Conda failded to create environment

### ISSUE THREAD

**Issue by nilesh-tawari** [nf-core/ampliseq#91]
To use pipeline with conda I am trying to create environment using the `environment.yml` file but it fails with following error,
```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - r-matrixstats=0.53.1
  - r-pillar=1.2.1 -> r-base[version='>=3.5.0,<3.5.1.0a0'] -> pango[version='>=1.42.1,<2.0a0']
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by d4straub** [comment]
You are right, this also doesn't work for me. I recommend using the singularity container, which requires singularity installation of course.
Sorry about that.

**Comment by apeltzer** [comment]
We adapted this in the latest commits to `dev`-  there were some packages shifted to specific conda channels that we didn't (because we didn't know about this kind of behavior) have in our current `environment.yml` for building the conda environment. 

This has now been addressed and is currently testing fine locally, Docker Image is updated in a couple of minutes - conda should work with the current `dev` branch, too. 

We'll release 1.1.0 addressing this today.
