### ISSUE TITLE
Conda environment error

### ISSUE THREAD

**Issue by bioinformatist** [nf-core/ampliseq#98]
Hi,
It seems conda env provided has some problems now.
The error occurs when calling dada2 in R, which may be caused by incompatible Rcpp version.
Below is my log. Thanks.
[nextflow.log](https://github.com/nf-core/ampliseq/files/3495011/nextflow.log)

**Comment by d4straub** [comment]
Hi,

that's sort of strange, because when I run `nextflow run nf-core/ampliseq -r master -profile conda,test` it runs (v1.1.0). Just tested it. Could you please use the above command and check? Just to make sure that the failure is not related to parameters or data.

Also, I would recommend using docker or singularity, that improves reproducibility.

**Comment by d4straub** [comment]
Closed because of lack of feedback.
